### ISSUE TITLE
Train a new plate type

### ISSUE THREAD

**Issue by changux** [AnjieZheng/Tensorflow-Number-Plate-Recognition#1]
Hi! 

How can we prepare a new model to understand a new plate type?

Thanks!

**Comment by AnjieCheng** [comment]
Hi,

Please refer to the original repository - [Deep-Anpr](https://github.com/matthewearl/deep-anpr) from Matthew Earl. You may generate your own training dataset so that the model learns a new plate type.

Thanks!
