### ISSUE TITLE
on running detect.py it shows Index Error

### ISSUE THREAD

**Issue by Thamizh-Sterio** [AnjieZheng/Tensorflow-Number-Plate-Recognition#3]
Traceback (most recent call last):
  File "detect.py", line 180, in <module>
    im = cv2.imread(sys.argv[1])
IndexError: list index out of range

**Comment by AnjieCheng** [comment]
Hi, did you pass the argument to the python script?
```script
./detect.py in.jpg weights.npz out.jpg
```

**Comment by Thamizh-Sterio** [comment]
i tried it..but it throws some other error.
Traceback (most recent call last):
  File "detect.py", line 189, in <module>
    pt1 = tuple(reversed(map(int, pt1)))
TypeError: argument to reversed() must be a sequence

**Comment by ghost** [comment]
I have similar error in that line: 'map' object is not reversible

**Comment by pkmantra** [comment]
Traceback (most recent call last):
  File "./detect.py", line 189, in <module>
    pt1 = tuple(reversed(map(int, pt1)))
TypeError: 'map' object is not reversible

i am facing the above issue

**Comment by sumitkuml** [comment]
map return an iterator object not list. typecast it into list before using reversed.
pt1 = tuple(reversed(list(map(int, pt1))))
